# 001-基础数学知识-1
------
“线性代数作为数学的一个分支，广泛应用于科学和工程中。然而，因为线性代数主要是面向连续数学，而非离散数学，所以很多计算机科学家很少接触它。掌握好线性代数对于理解和从事机器学习算法相关工作是很有必要的，尤其对于深度学习算法而言。因此，在开始介绍深度学习之前，我们集中探讨一些必备的线性代数知识。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 


## 1.1 标量

“标量 （scalar）：一个标量就是一个单独的数，它不同于线性代数中研究的其他大部分对象（通常是多个数的数组）。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 

乍一看可能比较绕，但它只是一个很简单的概念。比如我们在 `Python` 中表示：

In [3]:
a = 10
b = 5

上面的 `Python` 变量 `a` 和 `b` 都是标量。

## 1.2 向量

“向量 （vector）：一个向量是一列数。这些数是有序排列的。通过次序中的索引，我们可以确定每个单独的数。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 

假设有向量 $x$，$x$ 中标量的个数被称为向量 $x$ 的长度，记为 $n$。

我们使用 $x_{1}$ 表示向量 $x$ 中的第一个数，$x_{2}$ 表示向量 $x$ 中的第二个数，以此类推。

所以，一个长度为 $n$ 的向量 $x$ 各个元素可以被表示为 $\{x_{1}, x_{2}, ... , x{n} \}$。

> 注意：
> 
> 这里从逻辑上说明时，下标被默认为从 $1$ 开始，到 $n$ (包含)结束。
> 
> 但在实际开发中，我们的下标一般是从 $0$ 开始的，到 $n-1$ 结束。
> 
> 后面的矩阵和张量同理，就不再重复说明了。



我们试着在 `Python` 中表示向量，这里需要使用一个第三方扩展包 `Numpy`。

`Numpy` 支持高阶大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库，是目前最受欢迎度 `Python` 数据科学类库之一。

值得一提的是，`Numpy` 引入了多维数组以及可以直接有效率地操作多维数组的函数与运算符。因此在NumPy上只要能被表示为针对数组或矩阵运算的算法，其运行效率几乎都可以与编译过的等效C语言代码一样快，极大地缓解了 `Python` 在运行效率上的焦虑。

首先，如果没有安装 `Numpy`，先进行安装。

In [1]:
!pip install numpy

Looking in indexes: https://super-spider-1605756846230:****@aaronjny-pypi.pkg.coding.net/super-spider/super-spider/simple


引入 `Numpy` 包，惯用的方法是给 `Numpy` 设置一个别名，`np`。

In [2]:
import numpy as np

一个元素全为 `0`、长度为 `5` 的向量可以被表示如下：

In [4]:
x = np.array([0, 0, 0, 0, 0])
x

array([0, 0, 0, 0, 0])

我们也可以使用 `Numpy` 随机生成一个向量：

In [6]:
x = np.random.normal(size=(5,))
x

array([-0.6633077 , -0.30074044,  1.44198728,  0.14457244,  0.57128675])

## 1.3 矩阵

“矩阵 （matrix）：矩阵是一个二维数组，其中的每一个元素由两个索引（而非一个）所确定。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 

假设有 $ n*m $（惯用法，表示矩阵是 $n$ 行 $m$ 列的） 的矩阵 $M$, 我们使用 $M_{i,j}$ 表示矩阵 $M$ 第 $i$ 行第 $j$ 列的元素，所以左上角的元素可以被表示为 $M_{1,1}$，右下角的元素可以被表示为 $M_{n,m}$。

尝试使用 `Numpy` 创建一个随机矩阵：

In [7]:
m = np.random.normal(size=(3, 5))
m

array([[ 0.2416088 , -0.90430784,  0.05278803, -1.13333441,  0.8018479 ],
       [-1.18601861,  1.67189125, -0.72639164,  0.6000375 , -0.25478691],
       [ 0.04755629, -0.64918406,  1.85713531, -0.07952959, -1.7777632 ]])

左上角和右下角的元素分别为：

In [10]:
m[0][0],m[2],[4]

(0.2416088049463686,
 array([ 0.04755629, -0.64918406,  1.85713531, -0.07952959, -1.7777632 ]),
 [4])

我们也可以用这种方式表达左上角和右下角的元素，对于 `Numpy` 的 `Array` 对象来说，两者是等价的：

`m[i][j] == m[i, j]`

In [12]:
m[0,0],m[2,4]

(0.2416088049463686, -1.7777632048699445)

## 1.4 张量

“张量 （tensor）：在某些情况下，我们会讨论坐标超过两维的数组。一般的，一个数组中的元素分布在若干维坐标的规则网格中，我们称之为张量。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 

张量的概念与向量、矩阵类似。其实我们可以更直观地去理解它：


|概念|维数|
|--|--|
|标量|0|
|向量|1|
|矩阵|2|
|张量|>=3|

对于一个3维张量，其各维度下标分别为 $i,j,k$ 的元素表示为 $A_{i,j,k}$。

尝试使用 `Numpy` 生成一个随机的3维张量：



In [9]:
a = np.random.normal(size=(3, 4, 5))
a

array([[[-1.422351  , -0.81445904, -0.32605222,  0.63067177,
         -1.51142886],
        [ 0.25291515,  1.96998278,  0.45455653, -0.19563563,
         -2.10543648],
        [-2.71864637, -1.39599445,  0.31358409, -2.687218  ,
         -0.91560325],
        [-0.37024699,  0.8125057 ,  0.40114954,  0.9623359 ,
          1.24226105]],

       [[-0.43478423,  0.32916011, -0.00519804,  0.2390257 ,
         -0.51165795],
        [-0.73922966, -1.16927037, -0.15801901,  1.67778389,
         -0.5050908 ],
        [ 0.2739155 ,  0.56993305, -0.2111322 ,  0.82313957,
         -0.3981184 ],
        [ 0.28401076, -0.74120655, -0.66066145,  0.43476292,
          0.14471125]],

       [[ 0.46582396,  0.40072825,  1.01230498, -3.22709131,
         -0.13850476],
        [ 0.41275191,  0.38671517,  0.15693244,  0.31062141,
          1.02325171],
        [ 0.14358205,  0.14413912,  0.01649854,  0.30418405,
         -1.7001059 ],
        [-0.04956461,  0.42676036,  0.93792031, -1.36598371,
         -0

## 1.5 转置

“转置 （transpose）是矩阵的重要操作之一。矩阵的转置是以对角线为轴的镜像，这条从左上角到右下角的对角线被称为主对角线 （main diagonal）。”

摘录来自: [美]Ian Goodfellow（伊恩·古德费洛）. “深度学习。” Apple Books. 

通俗点来说，就是把一个矩阵的行变成列、列变成行。

以一个 $2*3$ 的矩阵为例，矩阵 $M$ 表示如下：

$$
M=\begin{bmatrix} 0 & 1 & 2\\ 3 & 4 & 5 \end{bmatrix}
$$

其转置矩阵 $M^{T}$ 表示如下：

$$
M^T=\begin{bmatrix} 0 & 3\\ 1 & 4\\ 2 & 5 \end{bmatrix}
$$

尝试使用 `Numpy` 实现：

In [15]:
m = np.array([[0, 1, 2], [3, 4, 5]])
print('矩阵 m :')
m

矩阵 m :


array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
mt = np.transpose(m)
print('矩阵 m 的转置:')
mt

矩阵 m 的转置:


array([[0, 3],
       [1, 4],
       [2, 5]])

再转置回去也是一样的，经过两次转置的矩阵和原矩阵是相等的：

In [17]:
m == np.transpose(mt)

array([[ True,  True,  True],
       [ True,  True,  True]])

再讨论一下标量和向量的转置。

标量可以看做只有一个元素的矩阵，因此它的转置就是它本身。

向量可以看作是只有一行（行向量）或一列（列向量）的矩阵，因此对向量的转置就是把行向量和列向量的互相转换。

三维及以上的张量我们一般不讨论转置问题，如果讨论，也是将其中的两维当做矩阵来讨论转置。